-- scripts/01_create_stage_and_pipe.sql

-- Create database & schema
CREATE OR REPLACE DATABASE INSURANCE_DB;
CREATE OR REPLACE SCHEMA POLICY_DATA;
USE DATABASE INSURANCE_DB;
USE SCHEMA POLICY_DATA;

-- Stage to S3 (replace placeholders!)
CREATE OR REPLACE STAGE POLICY_S3_STAGE
  URL='s3://insurance-data/'
  STORAGE_INTEGRATION = MY_S3_INTEGRATION
  FILE_FORMAT = (TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1);

-- Raw table
CREATE OR REPLACE TABLE RAW_POLICY_DATA (
  POLICY_ID INT,
  CUSTOMER_NAME STRING,
  POLICY_TYPE STRING,
  PREMIUM_AMOUNT NUMBER,
  STATUS STRING,
  LAST_UPDATED DATE
);

-- Snowpipe for auto-ingest
CREATE OR REPLACE PIPE POLICY_PIPE
  AUTO_INGEST = TRUE
AS
COPY INTO RAW_POLICY_DATA
FROM @POLICY_S3_STAGE
FILE_FORMAT = (TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1);
