-- scripts/02_create_streams_and_tasks.sql
USE DATABASE INSURANCE_DB;
USE SCHEMA POLICY_DATA;

-- Stream on raw table
CREATE OR REPLACE STREAM POLICY_STREAM ON TABLE RAW_POLICY_DATA;

-- Target table (analytics-ready)
CREATE OR REPLACE TABLE FINAL_POLICY_DATA AS
SELECT * FROM RAW_POLICY_DATA;

-- Hourly task to MERGE changes from stream
-- Replace COMPUTE_WH with your warehouse name
CREATE OR REPLACE TASK POLICY_TASK
  WAREHOUSE = COMPUTE_WH
  SCHEDULE = 'USING CRON 0 * * * * UTC'  -- runs at minute 0 every hour
AS
MERGE INTO FINAL_POLICY_DATA f
USING ( SELECT * FROM POLICY_STREAM ) s
ON f.POLICY_ID = s.POLICY_ID
WHEN MATCHED THEN UPDATE SET
  f.STATUS = s.STATUS,
  f.PREMIUM_AMOUNT = s.PREMIUM_AMOUNT,
  f.LAST_UPDATED = s.LAST_UPDATED,
  f.CUSTOMER_NAME = s.CUSTOMER_NAME,
  f.POLICY_TYPE = s.POLICY_TYPE
WHEN NOT MATCHED THEN INSERT (
  POLICY_ID, CUSTOMER_NAME, POLICY_TYPE, PREMIUM_AMOUNT, STATUS, LAST_UPDATED
) VALUES (
  s.POLICY_ID, s.CUSTOMER_NAME, s.POLICY_TYPE, s.PREMIUM_AMOUNT, s.STATUS, s.LAST_UPDATED
);

-- Start the task
ALTER TASK POLICY_TASK RESUME;
