-- scripts/03_validation_check.sql
USE DATABASE INSURANCE_DB;
USE SCHEMA POLICY_DATA;

CREATE OR REPLACE TABLE VALIDATION_REPORT AS
SELECT
  COUNT(*) AS TOTAL_RECORDS,
  COUNT(DISTINCT POLICY_ID) AS UNIQUE_POLICIES,
  SUM(CASE WHEN STATUS = 'Active' THEN 1 ELSE 0 END) AS ACTIVE_POLICIES,
  SUM(CASE WHEN STATUS = 'Lapsed' THEN 1 ELSE 0 END) AS LAPSED_POLICIES,
  CURRENT_TIMESTAMP() AS LAST_RUN_TIME
FROM FINAL_POLICY_DATA;
